// <auto-generated />
using System;
using FKFromAnotherDB.EFCore.SCADA;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace FKFromAnotherDB.Migrations
{
    [DbContext(typeof(ScadaDBContext))]
    partial class ScadaDBContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("FKFromAnotherDB.EFCore.SCADA.Models.BondSignalToTagEntity", b =>
                {
                    b.Property<Guid>("TagId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("SignalId")
                        .HasColumnType("uuid");

                    b.HasKey("TagId");

                    b.ToTable("BondSignalToTag");
                });

            modelBuilder.Entity("FKFromAnotherDB.EFCore.SCADA.Models.TagEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Property")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Tags");
                });

            modelBuilder.Entity("FKFromAnotherDB.EFCore.SCADA.Models.BondSignalToTagEntity", b =>
                {
                    b.HasOne("FKFromAnotherDB.EFCore.SCADA.Models.TagEntity", "TagEntity")
                        .WithOne("BondSignalToTagEntity")
                        .HasForeignKey("FKFromAnotherDB.EFCore.SCADA.Models.BondSignalToTagEntity", "TagId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("TagEntity");
                });

            modelBuilder.Entity("FKFromAnotherDB.EFCore.SCADA.Models.TagEntity", b =>
                {
                    b.Navigation("BondSignalToTagEntity");
                });
#pragma warning restore 612, 618
        }
    }
}
